# Generated by Django 4.2.20 on 2025-03-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(blank=True, max_length=10, null=True)),
                ('scheduled_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('mawb', models.CharField(max_length=20, unique=True)),
                ('flight_origin', models.CharField(blank=True, max_length=10, null=True)),
                ('flight_destination', models.CharField(blank=True, max_length=10, null=True)),
                ('pcs_awb', models.IntegerField(blank=True, null=True)),
                ('pcs_received', models.IntegerField(blank=True, null=True)),
                ('gross_weight', models.FloatField(blank=True, null=True)),
                ('commodity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('discrepancy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
