# Generated by Django 4.2.20 on 2025-03-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlinapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrecord',
            name='bt_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
