# Generated by Django 4.2.20 on 2025-03-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlinapp', '0002_flightrecord_bt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrecord',
            name='timestamp_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
