# Generated by Django 4.2.20 on 2025-03-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlinapp', '0003_flightrecord_timestamp_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrecord',
            name='trolley_staff_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
